import {language} from "../App";

export default {
    APP_TITLE: language === "en" ? "Avis de passage" : "Avis de passage",
    HOW_WAS_YOUR_LAST_DELIVERY: language === "en" ? "How was your last delivery?" : "Comment s’est passée ta dernière livraison?",
    OVERALL_RATING: language === "en" ? "Overall Rating" : "Note Globale",
    THE_OPINIONS: language === "en" ? "The Opinions" : "Les avis",
    NOTE_A_DELIVERY: language === "en" ? "NOTE A DELIVERY" : "NOTER UNE LIVRAISON",
    BY_COMPANY: language === "en" ? "By Company" : "Par Société",
    BY_CITY: language === "en" ? "By City" : "Par ville",
    REVIEWS: language === "en" ? "Reviews" : "Avis",
    EXPLORE: language === "en" ? "Explore" : "Explorer",
    AVERAGE_GRADES: language === "en" ? "Average Grades" : "Notes Moyenne",
    REVIEWS_BY_CITY: language === "en" ? "Reviews by city" : "Avis par ville",
    PROFILE: language === "en" ? "Profile" : "Profil",
    MY_REVIEWS: language === "en" ? "My review" : "Mes Avis",
    REQUIRED: language === "en" ? "Required" : "Requis",
    COMPANY: language === "en" ? "Company" : "Société",
    COMPANY_LIST: language === "en" ? "Company List" : "Liste Sociétés",
    SELECT_COMPANY: language === "en" ? "Select Company" : "Sélectionner une Société",
    DATE: language === "en" ? "Date" : "Date",
    SELECT_DATE: language === "en" ? "Select Date" : "Sélectionner une Date",
    NOTE: language === "en" ? "Note" : "Note",
    POSTAL_CODE: language === "en" ? "Postal Code" : "Code Postal",
    ENTER_POSTAL_CODE: language === "en" ? "Enter postal Code" : "Entrer un code postal",
    CITY: language === "en" ? "City" : "Ville",
    ENTER_CITY: language === "en" ? "Enter city" : "Entrer une ville",
    COMMENT: language === "en" ? "Comment" : "Commentaire",
    DELIVERY_PHOTO: language === "en" ? "Delivery photo" : "Photo de la livraison",
    ENTER_COMMENT: language === "en" ? "Enter comment" : "Écrire un commentaire",
    CHOOSE_AN_IMAGE: language === "en" ? "Choose an image" : "Choisir une image",
    ADDITIONAL_PHOTO: language === "en" ? "Additional photo" : "Photo complémentaire",
    PACKAGE_NUMBER: language === "en" ? "Package number" : "Numéro de Colis",
    ENTER_PACKAGE_NUMBER: language === "en" ? "Enter package number" : "Entrer le numéro de colis",
    SUBMIT_A_COMPLAINT: language === "en" ? "Submit a complaint" : "Transmettre en réclamation",
    EMAIL: language === "en" ? "Email" : "Email",
    ENTER_EMAIL: language === "en" ? "Enter email" : "Entrer l'e-mail",
    ENTER_YOUR_EMAIL: language === "en" ? "Enter your email" : "Entrer votre email",
    ENTER_YOUR_PASSWORD: language === "en" ? "Enter your password" : "Entrer votre mot de passe",
    SHOPPING_WEBSITE: language === "en" ? "Shopping website" : "Site d’Achat",
    ENTER_SHOPPING_WEBSITE: language === "en" ? "Enter shopping website (e.g., Amazon, CDiscount, Zalando)" : "ex: Amazon, CDiscount, Zalando",
    CANCEL_CAP: language === "en" ? "CANCEL" : "Annuler",
    OK: language === "en" ? "OK" : "Ok",
    CANCEL: language === "en" ? "Cancel" : "Annuler",
    DONE_CAP: language === "en" ? "DONE" : "Valider",
    TAKE_A_NEW_PHOTO: language === "en" ? "Take a new photo" : "Prendre une nouvelle photo",
    OPEN_GALLERY: language === "en" ? "Open Gallery" : "Ouvrir la galerie photo",
    PLEASE_SELECT_COMPANY_NAME: language === "en" ? "Please select company name" : "Sélectionner une société svp",
    PLEASE_FROM_EMAIL: language === "en" ? "Please enter from email address" : "Entrer une adresse mail svp",
    PLEASE_MESSAGE: language === "en" ? "Please enter message" : "Entrer un message svp",
    PLEASE_ENTER_POSTAL_CODE: language === "en" ? "Please enter postal code" : "Entrer un code postal svp",
    PLEASE_ENTER_CITY: language === "en" ? "Please enter city" : "Entrer une ville svp",
    RECENT_REVIEWS: language === "en" ? "Recent Reviews" : "Avis Récents",
    ALL_REVIEWS: language === "en" ? "All Reviews" : "Tous les avis",
    ABOUT_US: language === "en" ? "About Us" : "À propos",
    CHANGE_PROFILE_PHOTO: language === "en" ? "Change profile photo" : "Changer la photo de profil",
    TERM_CONDITIONS: language === "en" ? "Term & Conditions" : "Termes & Conditions",
    LANGUAGE: language === "en" ? "Change Language" : "Changer de langue",
    PRIVACY_POLICY: language === "en" ? "Privacy Policy" : "Politique de confidentialité",
    LOGIN: language === "en" ? "Log In" : "Se connecter",
    LOGOUT: language === "en" ? "Log Out" : "Se déconnecter",
    DELETE_ACCOUNT: language === "en" ? "Delete Account" : "Supprimer le compte",
    USER_NAME: language === "en" ? "User Name" : "Nom d’utilisateur",
    USER_EMAIL: language === "en" ? "User Email" : "Emaill",
    SIGN_IN_WITH_EMAIL: language === "en" ? "Sign In with email" : "Se connecter avec son email",
    SIGN_IN: language === "en" ? "Sign In" : "Se connecter",
    SIGN_UP_WITH_EMAIL: language === "en" ? "Sign Up with Email" : "S’inscrire avec son email",
    SIGN_UP: language === "en" ? "Sign Up" : "S’inscrire",
    NEW_USER_REGISTER: language === "en" ? "New user? Register" : "Nouvel utilisateur? S’inscrire ici",
    PASSWORD: language === "en" ? "Password" : "Mot de Passe",
    CONFIRM_PASSWORD: language === "en" ? "Confirm Password" : "Confirmer Mot de Passe",
    EMAIL_VALIDATION_MSG: language === "en" ? "Please enter your email" : "Entrer une adresse mail svpl",
    USERNAME_VALIDATION_MSG: language === "en" ? "Please enter user name" : "Entrer votre nom d’utilisateur svp",
    PASSWORD_VALIDATION_MSG: language === "en" ? "Please enter password" : "Entrer votre mot de passe svp",
    PASSWORD_CORRECT_VALIDATION_MSG: language === "en" ? "Please enter correct confirm password" : "Entrer un mot de passe correct svp",
    PASSWORD_LENGTH_VALIDATION_MSG: language === "en" ? "Password must be at least 8 characters long" : "Le Mot de passe doit avoir au moins 8 caractères",
    AUTH_EVENT: language === "en" ? "Auth" : "Authentification",
    SIGN_UP_EMAIL: language === "en" ? 'Sign Up with Email' : 'S’inscrire avec son email',
    EMAIL_SIGN_UP_TEXT: language === "en" ? 'Sign up with Email' : 'S’inscrire avec son email',
    EMAIL_SIGN_IN_TEXT: language === "en" ? 'Sign in with Email' : 'Se connecter avec son email',
    INVALID_VALIDATION_MSG: language === "en" ? "Invalid email/password!" : "Invalid email/mot de passe!",
    MANY_REQ_TITLE_MSG: language === "en" ?
        "Too many login attempts" : "Trop de tentatives de connexion",
    MANY_REQ_VALIDATION_MSG: language === "en" ? "Please wait a few minutes and try logging in again" : "Veuillez patienter quelques minutes et réessayez de vous connecter",
    SIGN_IN_EMAIL: language === "en" ? 'Sign In with Email' : 'Se connecter avec son email',
    EMAIL_ALREADY_VALIDATION_MSG: language === "en" ? "Email address is already in use" : "Adresse email déjà utilisée",
    EMAIL_INVALID_VALIDATION_MSG: language === "en" ? "Email address is invalid" : "Adresse email invalide",
    ACCOUNT_DELETED: language === "en" ? "Account deleted" : "Compte supprimé",
    ACCOUNT_DELETED_MESSAGE: language === "en" ? "Your account has been deleted. Please contact support for assistance" : "Votre compte a été supprimé. Veuillez contacter le support en cas de besoin",
    BTN_RESEND: language === "en" ? "Resend email" : "Renvoyer le mail",
    BTN_LOGIN: language === "en" ? "Login" : "Se connecter",
    BTN_PROCEED: language === "en" ? "Proceed" : "Envoyé",
    VERIFICATION_ALERT_TITLE: language === "en" ? "Email verification required" : "Mail de vérification envoyé",
    VERIFICATION_MESSAGE: language === "en" ? "Please check your email first to confirm your email address, then return to the app and press the proceed button to continue with the sign-up process" : "Merci de confirmer votre compte via le mail de confirmation envoyé sur votre boite mail, puis revenez à l'application et appuyez sur le bouton pour poursuivre le processus d'inscription",
    YOUR_FEEDBACK_SENT: language === "en" ? "Your feedback sent" : "Avis envoyé",
    EMAIL_VERIFICATION_MSG: language === "en" ? "Your mail hasn’t been verified yet" : "Votre mail n’a pas encore été vérifié",
    EARNING_POINTS: language === "en" ? "Earning Points" : "Points",
    DESCRIPTION: language === "en" ? "Description" : "Description",
    AUTHOR: language === "en" ? "Author" : "Auteur",
    BEN: language === "en" ? "Ben" : "Ben",
    SHARE: language === "en" ? "Author" : "Auteur",
    SHARE_TXT: language === "en" ? "Play store link" : "Lien Store",
    SUPPORT: language === "en" ? "Support" : "Support",
    SEND_FEEDBACK: language === "en" ? "Send Feedback" : "Envoyer un retour d’expérience",
    SEND_FEEDBACK_: language === "en" ? "Send Feedback >" : "Feedback envoyé >",
    FROM: language === "en" ? "From" : "De",
    MESSAGE: language === "en" ? "Message" : "Message",
    NO_REVIEW_FOUND: language === "en" ? "No review found" : "Aucun avis trouvé",
    DELETE_MESSAGE: language === "en" ? "Are you sure you want to proceed with deleting your account?" : "Êtes-vous sûr de vouloir procéder à la suppression de votre compte?",
    BUTTON_YES: language === "en" ? "Yes" : "Oui",
    BUTTON_NO: language === "en" ? "No" : "Non",
    BACK: language === "en" ? "Back" : "Back",
    FRENCH: language === "en" ? "French" : "Français",
    ENGLISH: language === "en" ? "English" : "Anglaise",
}
