export default {
    APP_TITLE: "Avis de passage",
    HOW_WAS_YOUR_LAST_DELIVERY: "Comment s’est passée ta dernière livraison?",
    OVERALL_RATING: " Note Globale",
    THE_OPINIONS: "Les avis",
    NOTE_A_DELIVERY: "NOTER UNE LIVRAISON ",
    BY_COMPANY: "Par Société",
    BY_CITY: "Par ville",
    REVIEWS: "Avis",
    EXPLORE: "Explorer",
    AVERAGE_GRADES: "Notes Moyenne",
    REVIEWS_BY_CITY: "Avis par ville",
    PROFILE: "Profil",
    MY_REVIEWS: "Mes Avis",
    REQUIRED: "Requis",
    COMPANY: "Société",
    COMPANY_LIST: "Liste Sociétést",
    SELECT_COMPANY: "Sélectionner une Société",
    DATE: "Date",
    SELECT_DATE: "Sélectionner une Date",
    NOTE: "Note",
    POSTAL_CODE: "Code Postal",
    ENTER_POSTAL_CODE: "Entrer un code postal",
    CITY: "Ville",
    ENTER_CITY: "Entre une ville",
    COMMENT: "Commentaire",
    DELIVERY_PHOTO: "Photo de la livraison",
    ENTER_COMMENT: "Écrire un commentaire",
    CHOOSE_AN_IMAGE: "Choisir une image",
    ADDITIONAL_PHOTO: "Photo complémentaire",
    PACKAGE_NUMBER: "Numéro de Colis",
    ENTER_PACKAGE_NUMBER: "Entrer le numéro de colis",
    SUBMIT_A_COMPLAINT: "Transmettre en réclamation",
    EMAIL: "Email",
    ENTER_EMAIL: "Entrer votre email",
    ENTER_YOUR_EMAIL: "Entrer votre email",
    ENTER_YOUR_PASSWORD: "Entrer votre mot de passe",
    SHOPPING_WEBSITE: "Site d’Achat",
    ENTER_SHOPPING_WEBSITE: "ex: Amazon, CDiscount, Zalando",
    CANCEL_CAP: "ANNULER",
    OK: "Ok",
    CANCEL: "Annuler ",
    DONE_CAP: "Valider",
    TAKE_A_NEW_PHOTO: "Prendre une nouvelle photo",
    OPEN_GALLERY: "Ouvrir la galerie photo",
    PLEASE_SELECT_COMPANY_NAME: "Sélectionner une société svp",
    PLEASE_FROM_EMAIL: "Entrer une adresse mail svp",
    PLEASE_MESSAGE: "Entrer un message svp",
    PLEASE_ENTER_POSTAL_CODE: "Entrer un code postal svp",
    PLEASE_ENTER_CITY: "Entrer une ville svp",
    RECENT_REVIEWS: "Avis Récents",
    ALL_REVIEWS: "Tous les avis",
    ABOUT_US: "À propos ",
    CHANGE_PROFILE_PHOTO: "Changer la photo de profil",
    TERM_CONDITIONS: "Termes & Conditions",
    PRIVACY_POLICY: "Politique de confidentialité",
    LOGIN: "Se connecter",
    LOGOUT: "Se déconnecter",
    DELETE_ACCOUNT: "Supprimer le compte",
    USER_NAME: "Nom d’utilisateur",
    USER_EMAIL: "Emaill",
    SIGN_IN_WITH_EMAIL: "Se connecter avec son email",
    SIGN_IN: "Se connecter",
    SIGN_UP_WITH_EMAIL: "S’inscrire avec son email",
    SIGN_UP: "S’inscrire",
    NEW_USER_REGISTER: "Nouvel utilisateur? S’inscrire ici",
    PASSWORD: "Mot de Passe",
    CONFIRM_PASSWORD: "Confirmer Mot de Passe",
    EMAIL_VALIDATION_MSG: "Entrer une adresse mail svpl",
    USERNAME_VALIDATION_MSG: "Entrer votre nom d’utilisateur svp",
    PASSWORD_VALIDATION_MSG: "Entrer votre mot de passe svp",
    PASSWORD_CORRECT_VALIDATION_MSG: "Entrer un  mot de passe correct svp",
    PASSWORD_LENGTH_VALIDATION_MSG: "Le Mot de passe doit avoir au moins 8 caractères",
    AUTH_EVENT: "Authentification",
    SIGN_UP_EMAIL: 'S’inscrire avec son email',
    EMAIL_SIGN_UP_TEXT: 'S’inscrire avec son email',
    EMAIL_SIGN_IN_TEXT: 'Se connecter avec son email',
    INVALID_VALIDATION_MSG: "Invalid email/mot de passe!",
    MANY_REQ_TITLE_MSG: "Too many login attempts",
    MANY_REQ_VALIDATION_MSG: "Please wait a few minutes and try logging in again",
    SIGN_IN_EMAIL: 'Se connecter avec son email',
    EMAIL_ALREADY_VALIDATION_MSG: "Email déjà utilisé",
    EMAIL_INVALID_VALIDATION_MSG: " email invalide",
    ACCOUNT_DELETED: " Compte supprimé",
    ACCOUNT_DELETED_MESSAGE: " Votre compte a été supprimé. Contacter le support si besoin",
    BTN_RESEND: " Renvoyer le mail",
    BTN_LOGIN: " Se connecter",
    BTN_PROCEED: " Envoyé",
    VERIFICATION_ALERT_TITLE: "Mail de vérification envoyé",
    VERIFICATION_MESSAGE: "Merci de confirmer votre compte via le mail de confirmation envoyé sur votre boite mail",
    YOUR_FEEDBACK_SENT: "Avis envoyé ",
    EMAIL_VERIFICATION_MSG: "Votre mail n’a pas encore été vérifié ",
    EARNING_POINTS: "Points",
    DESCRIPTION: "Description",
    AUTHOR: "Auteur",
    BEN: "Ben",
    SHARE: "Auteur",
    SHARE_TXT: "Lien Store",
    SUPPORT: "Support",
    SEND_FEEDBACK: "Envoyer un retour d’expérience",
    SEND_FEEDBACK_: "Feedback envoyé >",
    FROM: "De",
    MESSAGE: "Message",
    NO_REVIEW_FOUND: "Message",
}
